# Generated by Django 3.0.5 on 2020-06-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200621_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='owner',
        ),
    ]
