# Generated by Django 3.0.5 on 2020-06-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_shoppinglist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='gramaj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='magazin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
