# Generated by Django 3.0.5 on 2020-06-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200626_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
