# Generated by Django 3.0.5 on 2020-06-27 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_shoppingitem_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='owner',
            field=models.ManyToManyField(related_name='shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
