# Generated by Django 3.0.5 on 2020-06-27 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_shoppinglist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
